[package]
name = "core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
uuid.workspace = true
serde.workspace = true
tokio.workspace = true
async-trait = "0.1.88"
dirs = "6.0.0"
toml = "0.8.23"
wasmtime = "34.0.1"
wasmtime-wasi = "=34.0.1"
