[package]
name = "cognito-finder"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
serde.workspace = true
tokio.workspace = true
log.workspace = true
nucleo = "0.5.0"
walkdir = "2.5.0"
